spring:
  application:
    name: caicara-back-end
  web:
    locale: pt_BR
  datasource:
    url: ${DATABASE_URL} #"jdbc:postgresql://localhost:5432/caicara_db?useSSL=false&serverTimezone=America/Sao_paulo" #${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update